### PR TITLE
Add server-side logic to skip validation for hidden fields

### PR DESCRIPTION
**Pull request by stevish-com**
This allows users to create a field that is hidden under certain conditions, but required when visible. This is done by running the show/hide field logic server-side on form submission, removing hidden fields from the post data, and turning off validation for those fields (preventing an error for "required" hidden fields that were not filled out)

### CODE REVIEW

**Comment by stevish-com** [comment]
I think this would be beneficial for all users, especially since this is the topic of more than one negative review. Also, we'd like to use this plugin, but this absolutely must be addressed first, since we will need required fields that can be hidden.

I tried to comment the code extensively to be transparent in what is being done, but let me know if you have any questions about how it works.

Email is another thing that we'd like to figure out a fix for before implementing this plugin (meaning the ability to hide parts of the emails as well), but it's not as high of a priority as this

**Comment by pwkip** [comment]
awesome! on fist sight the code looks pretty clean. i don't have much time for the moment (as you noticed maybe.. it's been over a month since i replied to any support threads) but i will do my best to review and test the code, and will definitely include it in the next update, so you can go ahead and implement your version for now. i'll make sure it doesn't break with the next update.

thanks for you're efforts. i'll try and find some time to merge this soon and release it in the next version.

**Comment by stevish-com** [comment]
If you haven't looked at this yet, would you mind holding off on implementing it? I put the new functions outside of the class (for fear of messing with your class), but that made me need to use $GLOBALS for some stuff which really would be done better as class variables. So I've moved the functions inside the class, added the necessary private variables, and am in the middle of adding support for adding groups to the emails (to hide portions of the notification emails based on which groups are hidden). I'll either generate a new pull request or modify this one when I'm done, if that's possible.

**Comment by pwkip** [comment]
ok. didnt find the time yet so yeah that would be great!

**Pull request closed without merging**
